export const products = [
  { slug: "business-cards", name: "Business Cards", size: "3.5 x 2 in", description: "Fast, premium cards with polished starter layouts.", methods: ["template", "upload"] },
  { slug: "flyers", name: "Flyers", size: "8.5 x 11 in", description: "Promotional flyers with bold hero layouts.", methods: ["template", "upload"] },
  { slug: "banners", name: "Banners", size: "6 x 3 ft", description: "Large-format banners with event-ready compositions.", methods: ["template", "upload"] },
  { slug: "postcards", name: "Postcards", size: "6 x 4 in", description: "Compact direct-mail and promo card layouts.", methods: ["template", "upload"] },
];

export const templates = [
  { id: "bc-modern-blue", product: "business-cards", title: "Modern Blue", category: "Modern", accent: "#1d4ed8", bg: "#eff6ff", headline: "Bold first impression", subheadline: "Clean professional business card", cta: "Book today", previewShape: "card", imageStyle: "none" },
  { id: "bc-luxury-black", product: "business-cards", title: "Luxury Black", category: "Luxury", accent: "#d4af37", bg: "#111111", headline: "Premium identity", subheadline: "Elegant dark business card", cta: "Call now", previewShape: "card", imageStyle: "none" },
  { id: "bc-real-estate", product: "business-cards", title: "Real Estate", category: "Real Estate", accent: "#0f766e", bg: "#ecfeff", headline: "List. Sell. Close.", subheadline: "High-trust realtor card", cta: "Schedule a showing", previewShape: "card", imageStyle: "photo" },
  { id: "bc-beauty-blush", product: "business-cards", title: "Beauty Blush", category: "Beauty", accent: "#db2777", bg: "#fdf2f8", headline: "Glow with confidence", subheadline: "Soft, feminine salon layout", cta: "Book a session", previewShape: "card", imageStyle: "soft" },
  { id: "bc-construction", product: "business-cards", title: "Construction Pro", category: "Construction", accent: "#ea580c", bg: "#fff7ed", headline: "Built to last", subheadline: "Trade-focused service card", cta: "Free estimate", previewShape: "card", imageStyle: "none" },
  { id: "bc-minimal-white", product: "business-cards", title: "Minimal White", category: "Minimal", accent: "#0f172a", bg: "#ffffff", headline: "Simple. Sharp. Trusted.", subheadline: "Minimalist professional card", cta: "Let's connect", previewShape: "card", imageStyle: "none" },

  { id: "fl-restaurant-red", product: "flyers", title: "Restaurant Promo", category: "Restaurant", accent: "#dc2626", bg: "#fef2f2", headline: "Grand opening special", subheadline: "Bold local promotion flyer", cta: "Order today", previewShape: "flyer", imageStyle: "photo" },
  { id: "fl-corporate-clean", product: "flyers", title: "Corporate Clean", category: "Corporate", accent: "#1e3a8a", bg: "#eff6ff", headline: "Professional services that scale", subheadline: "Service-led flyer for modern brands", cta: "Get a quote", previewShape: "flyer", imageStyle: "none" },
  { id: "fl-event-neon", product: "flyers", title: "Event Neon", category: "Modern", accent: "#7c3aed", bg: "#faf5ff", headline: "This weekend only", subheadline: "Eye-catching event flyer layout", cta: "Reserve your spot", previewShape: "flyer", imageStyle: "soft" },
  { id: "fl-church-classic", product: "flyers", title: "Church Classic", category: "Community", accent: "#2563eb", bg: "#eff6ff", headline: "Join us this Sunday", subheadline: "Welcoming church and ministry flyer", cta: "All are welcome", previewShape: "flyer", imageStyle: "none" },
  { id: "fl-construction-sale", product: "flyers", title: "Construction Special", category: "Construction", accent: "#d97706", bg: "#fffbeb", headline: "Licensed. Bonded. Insured.", subheadline: "Trade flyer built for conversions", cta: "Free estimate", previewShape: "flyer", imageStyle: "none" },
  { id: "fl-beauty-editorial", product: "flyers", title: "Beauty Editorial", category: "Beauty", accent: "#be185d", bg: "#fdf2f8", headline: "Refresh your look", subheadline: "Beauty promotion with premium spacing", cta: "Book now", previewShape: "flyer", imageStyle: "photo" },

  { id: "bn-ocean-wave", product: "banners", title: "Ocean Wave", category: "Modern", accent: "#0284c7", bg: "#e0f2fe", headline: "Big message. Clean design.", subheadline: "Wide-format banner with bold wave motif", cta: "Visit us today", previewShape: "banner", imageStyle: "soft" },
  { id: "bn-luxury-gold", product: "banners", title: "Luxury Gold", category: "Luxury", accent: "#d4af37", bg: "#171717", headline: "A premium brand presence", subheadline: "Dark luxury banner for upscale offers", cta: "Now open", previewShape: "banner", imageStyle: "none" },
  { id: "bn-real-estate-openhouse", product: "banners", title: "Open House", category: "Real Estate", accent: "#059669", bg: "#ecfdf5", headline: "Open House Today", subheadline: "Directional open-house banner", cta: "Tour this home", previewShape: "banner", imageStyle: "photo" },
  { id: "bn-church-revival", product: "banners", title: "Church Revival", category: "Community", accent: "#4338ca", bg: "#eef2ff", headline: "Community Revival Weekend", subheadline: "High-visibility event banner", cta: "Join us", previewShape: "banner", imageStyle: "soft" },
  { id: "bn-construction-yard", product: "banners", title: "Construction Yard", category: "Construction", accent: "#f59e0b", bg: "#fef3c7", headline: "Safety. Quality. Speed.", subheadline: "Outdoor banner for active job sites", cta: "Call for service", previewShape: "banner", imageStyle: "none" },
  { id: "bn-restaurant-grand", product: "banners", title: "Grand Opening Banner", category: "Restaurant", accent: "#dc2626", bg: "#fef2f2", headline: "Grand Opening", subheadline: "Street-facing banner for food and beverage brands", cta: "Dine with us", previewShape: "banner", imageStyle: "photo" },

  { id: "pc-minimal-mailer", product: "postcards", title: "Minimal Mailer", category: "Minimal", accent: "#334155", bg: "#f8fafc", headline: "A direct message that lands", subheadline: "Clean postcard with strong CTA", cta: "Learn more", previewShape: "postcard", imageStyle: "none" },
  { id: "pc-beauty-promo", product: "postcards", title: "Beauty Promo", category: "Beauty", accent: "#e11d48", bg: "#fff1f2", headline: "Spring glow special", subheadline: "Postcard for salons, spas, and skincare", cta: "Claim your offer", previewShape: "postcard", imageStyle: "photo" },
  { id: "pc-real-estate-listing", product: "postcards", title: "Property Showcase", category: "Real Estate", accent: "#0284c7", bg: "#f0f9ff", headline: "Just listed in your neighborhood", subheadline: "Property postcard with listing appeal", cta: "Scan to view", previewShape: "postcard", imageStyle: "photo" },
  { id: "pc-restaurant-coupon", product: "postcards", title: "Restaurant Coupon", category: "Restaurant", accent: "#dc2626", bg: "#fff7ed", headline: "Bring this in for 20% off", subheadline: "Local promo postcard with coupon styling", cta: "Redeem today", previewShape: "postcard", imageStyle: "soft" },
  { id: "pc-church-invite", product: "postcards", title: "Church Invite", category: "Community", accent: "#4f46e5", bg: "#eef2ff", headline: "You're invited", subheadline: "Welcoming postcard for ministry outreach", cta: "Join us Sunday", previewShape: "postcard", imageStyle: "none" },
  { id: "pc-corporate-announcement", product: "postcards", title: "Corporate Announcement", category: "Corporate", accent: "#1d4ed8", bg: "#eff6ff", headline: "New location. Same trusted team.", subheadline: "Business announcement postcard", cta: "Visit today", previewShape: "postcard", imageStyle: "none" },
];
